[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "/"
  to = "/chat/chat.html"
  status = 200
  force = false
[[redirects]]
  from = "/index.html"
  to = "/chat/chat.html"
  status = 200
  force = false